name: action_name

on:
    push:
        branches: ['branch_name']
    pull_request:
        branches: '*'

jobs:
    build-package:
        runs-on: ubuntu-latest
        if: ${{ github.ref != 'refs/heads/branch_name' }}
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
            - name: install dependencies
              run: npm ci
            - name: run build
              run: npm run build --if-present
            - name: run tests
              run: npm test --if-present

    publish-gh-package:
        runs-on: ubuntu-latest
        if: ${{ github.ref == 'refs/heads/branch_name' }}
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 18
                  registry-url: https://npm.pkg.github.com/
                  scope: '@USER'
            - name: install dependencies
              run: npm ci
            - name: run build
              run: npm run build --if-present
            - name: run tests
              run: npm test --if-present
            - name: run semantic-release
              run: npm run semantic-release
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
